version: '3.6'
services:
  lumen:
    build: .
    container_name: lumen
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - lumen-postgres
  lumen-postgres:
    image: "postgres:11.2"
    container_name: "lumen-postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
